### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by r58Playz** [boskee/Minecraft#108]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 249, in _safe_alloc
    return self.allocator.alloc(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\allocation.py", line 195, in alloc
    raise AllocatorMemoryException(self.capacity + size - free_size)
pyglet.graphics.allocation.AllocatorMemoryException: 2097168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/toshi/MicroHat/applications/games/factories/astrocraft-renovation/main.py", line 167, in <module>
    main(options)
  File "C:/Users/toshi/MicroHat/applications/games/factories/astrocraft-renovation/main.py", line 139, in main
    pyglet.app.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 275, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\clock.py", line 346, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 310, in process_queue
    self.packetreceiver.dequeue_packet()
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\client.py", line 104, in dequeue_packet
    blocks.show_block(position)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 201, in show_block
    self._show_block(position, block)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 234, in _show_block
    ('c3f/static', color_data))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\__init__.py", line 370, in add
    vlist = domain.create(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 279, in create
    start = self._safe_alloc(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 254, in _safe_alloc
    buffer.resize(capacity * buffer.element_size)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 431, in resize
    data = (ctypes.c_byte * size)()
MemoryError

**Comment by r58Playz** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 249, in _safe_alloc
    return self.allocator.alloc(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\allocation.py", line 195, in alloc
    raise AllocatorMemoryException(self.capacity + size - free_size)
pyglet.graphics.allocation.AllocatorMemoryException: 2097168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/toshi/MicroHat/applications/games/factories/astrocraft-renovation/main.py", line 167, in <module>
    main(options)
  File "C:/Users/toshi/MicroHat/applications/games/factories/astrocraft-renovation/main.py", line 139, in main
    pyglet.app.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 275, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\clock.py", line 346, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 310, in process_queue
    self.packetreceiver.dequeue_packet()
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\client.py", line 104, in dequeue_packet
    blocks.show_block(position)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 201, in show_block
    self._show_block(position, block)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 234, in _show_block
    ('c3f/static', color_data))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\__init__.py", line 370, in add
    vlist = domain.create(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 279, in create
    start = self._safe_alloc(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 254, in _safe_alloc
    buffer.resize(capacity * buffer.element_size)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 431, in resize
    data = (ctypes.c_byte * size)()
MemoryError
```

**Comment by r58Playz** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 249, in _safe_alloc
    return self.allocator.alloc(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\allocation.py", line 195, in alloc
    raise AllocatorMemoryException(self.capacity + size - free_size)
pyglet.graphics.allocation.AllocatorMemoryException: 2097168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/toshi/MicroHat/applications/games/factories/astrocraft-renovation/main.py", line 167, in <module>
    main(options)
  File "C:/Users/toshi/MicroHat/applications/games/factories/astrocraft-renovation/main.py", line 139, in main
    pyglet.app.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\app\base.py", line 275, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\clock.py", line 346, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 310, in process_queue
    self.packetreceiver.dequeue_packet()
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\client.py", line 104, in dequeue_packet
    blocks.show_block(position)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 201, in show_block
    self._show_block(position, block)
  File "C:\Users\toshi\MicroHat\applications\games\factories\astrocraft-renovation\world.py", line 234, in _show_block
    ('c3f/static', color_data))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\__init__.py", line 370, in add
    vlist = domain.create(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 279, in create
    start = self._safe_alloc(count)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexdomain.py", line 254, in _safe_alloc
    buffer.resize(capacity * buffer.element_size)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 431, in resize
    data = (ctypes.c_byte * size)()
MemoryError
```
