### ISSUE TITLE
problem running setup.py

### ISSUE THREAD

**Issue by nickums** [boskee/Minecraft#110]
Running setup.py  to try to get into this wonderful project, I get:

Warning (from warnings module):
  File "C:\Python\Python36\lib\site-packages\distutils\dist.py", line 261
    warnings.warn(msg)
UserWarning: Unknown distribution option: 'executables'

**Comment by r58Playz** [comment]
You should use 'python3 main.py' to run the project, you should use
'python3 server.py' to run the server, and you should use 'python3 setup.py
build_exe' to build the executable. Also, cython and cx_Freeze must be
installed to build the executable.

**Comment by nickums** [comment]
Many thanks for clarifying the install requirements.  So far so good.
On executing main.py I get ;
Traceback (most recent call last):
  File "C:\Python\Python36\GitHub\Minecraft-master\Minecraft-master\main.py", line 22, in <module>
    from controllers import MainMenuController
  File "C:\Python\Python36\GitHub\Minecraft-master\Minecraft-master\controllers.py", line 21, in <module>
    from blocks import *
  File "C:\Python\Python36\GitHub\Minecraft-master\Minecraft-master\blocks.py", line 1785, in <module>
    cactus_block = CactusBlock()
  File "C:\Python\Python36\GitHub\Minecraft-master\Minecraft-master\blocks.py", line 276, in __init__
    self.update_texture()
  File "C:\Python\Python36\GitHub\Minecraft-master\Minecraft-master\blocks.py", line 353, in update_texture
    self.group = TextureGroupIndividual(self.texture_name, self.height, self.width)
  File "C:\Python\Python36\GitHub\Minecraft-master\Minecraft-master\blocks.py", line 100, in __init__
    for j in (0, 6): self.texture_data[i * 8 + j] += w_margin
IndexError: list index out of range

So something wrong with one specific texture. I'll try and figure it out.
 Let's close this and thanks again for your prompt and helpful response.
