### ISSUE TITLE
No Module named PIL

### ISSUE THREAD

**Issue by kellyfj** [boskee/Minecraft#81]
Running OS/X 10.8.5

Franks-MacBook-Pro:Minecraft frankkelly$ python --version
Python 2.7.2

The fogleman original branch works fine on my Mac so not sure what I am missing 

```
Franks-MacBook-Pro:Minecraft frankkelly$ arch -i386 python main.py
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from controllers import MainMenuController
  File "/usr/local/coderdojo/python/pycraftr/Minecraft/controllers.py", line 21, in <module>
    from blocks import *
  File "/usr/local/coderdojo/python/pycraftr/Minecraft/blocks.py", line 24, in <module>
    from textures import TexturePackList
  File "/usr/local/coderdojo/python/pycraftr/Minecraft/textures.py", line 6, in <module>
    from PIL import Image
ImportError: No module named PIL
```

Also not sure what PIL is but I _think_ I successfully installed it too (just in case)

```
Franks-MacBook-Pro:Minecraft frankkelly$ sudo easy_install PIL
Password:
Searching for PIL
Best match: PIL 1.1.7
Processing PIL-1.1.7-py2.7-macosx-10.8-intel.egg
PIL 1.1.7 is already the active version in easy-install.pth
Installing pilconvert.py script to /usr/local/bin
Installing pildriver.py script to /usr/local/bin
Installing pilfile.py script to /usr/local/bin
Installing pilfont.py script to /usr/local/bin
Installing pilprint.py script to /usr/local/bin

Using /Library/Python/2.7/site-packages/PIL-1.1.7-py2.7-macosx-10.8-intel.egg
Processing dependencies for PIL
Finished processing dependencies for PIL
```

**Comment by r1chardj0n3s** [comment]
"pip install pillow" is a better solution to the PIL installation.

**Comment by AlexCerome** [comment]
map code！

**Comment by ocarneiro** [comment]
pillow has some issues on recent versions. A better solution is to provide a "safe" version, like:
    pip install pillow==2.6.1

**Comment by r58Playz** [comment]
just run
`pip install pillow`

**Comment by Nebual** [comment]
Amusingly, we don't actually use PIL, it was a stray import all along.

**Comment by r58Playz** [comment]
I thought we used it in `main.py`. I got a ImportError since I had forgotten to install pillow.
